language: cpp
dist: bionic
compiler:
  - gcc
  # - clang 

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Codecov
  - sudo pip install codecov
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check
  # OCLint
  - ./install_oclint
  # Others
  - ./download_other_githubs

services:
 - xvfb

script: 
  # Console
  - qmake ConnectThreeConsole.pro
  - make debug --silent
  - ./ConnectThreeConsole
  # Console Test
  - qmake ConnectThreeConsoleTest.pro
  - make debug --silent
  - ./ConnectThreeConsoleTest
  # Desktop
  - qmake ConnectThreeDesktop.pro
  - make --silent
  - ./ConnectThreeDesktop &
  - sleep 10
  - sudo killall ConnectThreeDesktop
  # Desktop test
  - qmake ConnectThreeDesktopTest.pro
  - make debug --silent
  - ./ConnectThreeDesktopTest
  # Codecov
  - ./get_code_cov
  - codecov
  # Check dead links
  - rm .travis.yml
  - ./scripts/check_dead_links || true
  # OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)
