#############################################################################
# Makefile for building: ConnectThreeWebsite
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  ConnectThreeWebsite.pro
# Template: app
# Command: /home/p230198/GitHubs/RibiLibraries/mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5 -o Makefile ConnectThreeWebsite.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = /home/p230198/GitHubs/RibiLibraries/mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: ConnectThreeWebsite.pro ../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/win32-g++/qmake.conf ../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_pre.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/qdevice.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/device_config.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/qconfig.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3d.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3d_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axbase.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axbase_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axcontainer.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axserver.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axserver_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_declarative.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_enginio.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_help.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_help_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_location.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_location_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_nfc.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioning.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_script.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_script_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sensors.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uitools.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_websockets.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_winextras.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_winextras_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xlsx.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xlsx_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_dsengine.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qdds.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qicns.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qico.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjp2.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qminimal.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmng.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlite.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlmysql.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlpsql.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqltds.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvg.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtaudio_windows.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtga.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtiff.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwbmp.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwebp.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindows.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_functions.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_config.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/qt_config.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/win32-g++/qmake.conf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_post.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_pre.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/default_pre.prf \
		../RibiLibraries/BoostAll.pri \
		../RibiLibraries/Wt.pri \
		../RibiLibraries/WebApplication.pri \
		../RibiClasses/CppAbout/CppAbout.pri \
		../RibiClasses/CppFileIo/CppFileIo.pri \
		../RibiClasses/CppHelp/CppHelp.pri \
		../RibiClasses/CppMenuDialog/CppMenuDialog.pri \
		../RibiClasses/CppTestTimer/CppTestTimer.pri \
		../RibiClasses/CppTrace/CppTrace.pri \
		../RibiLibraries/GeneralConsole.pri \
		../RibiClasses/CppWtAboutDialog/CppWtAboutDialog.pri \
		../RibiClasses/CppWtAutoConfig/CppWtAutoConfig.pri \
		../RibiLibraries/GeneralWeb.pri \
		../RibiClasses/CppCanvas/CppCanvas.pri \
		../RibiClasses/CppConnectThree/CppConnectThree.pri \
		../RibiClasses/CppConnectThreeWidget/CppConnectThreeWidget.pri \
		../RibiClasses/CppDotMatrix/CppDotMatrix.pri \
		../RibiClasses/CppTextCanvas/CppTextCanvas.pri \
		../RibiClasses/CppWtConnectThreeWidget/CppWtConnectThreeWidget.pri \
		ConnectThreeConsole.pri \
		ConnectThreeWebsite.pri \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resolve_config.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds_post.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_post.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/console.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/rtti.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/precompile_header.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/warn_on.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resources.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/moc.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/opengl.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/testcase_targets.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exceptions.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/yacc.prf \
		../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/lex.prf \
		ConnectThreeWebsite.pro \
		/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Gui.prl \
		/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Core.prl \
		/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/platforms/qwindows.prl \
		/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qdds.prl \
		/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qicns.prl \
		/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qico.prl \
		/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qjp2.prl \
		/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qmng.prl \
		/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qtga.prl \
		/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qtiff.prl \
		/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qwbmp.prl \
		/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qwebp.prl
	$(QMAKE) -o Makefile ConnectThreeWebsite.pro
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_pre.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/qdevice.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/device_config.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/qconfig.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3d.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3d_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquick.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axbase.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axbase_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axcontainer.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axcontainer_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axserver.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axserver_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_declarative.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_declarative_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_enginio.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_help.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_help_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_location.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_location_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_nfc.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioning.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_script.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_script_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scripttools.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sensors.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialport.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serviceframework.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_systeminfo.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uitools.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webchannel.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_websockets.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_winextras.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_winextras_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xlsx.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xlsx_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_dsengine.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qdds.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qicns.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qico.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjp2.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qminimal.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmng.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qnativewifibearer.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlite.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlmysql.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlodbc.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlpsql.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqltds.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvg.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvgicon.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtaudio_windows.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtga.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtiff.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwbmp.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwebp.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindows.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_functions.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_config.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/qt_config.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/win32-g++/qmake.conf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_post.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_pre.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/default_pre.prf:
../RibiLibraries/BoostAll.pri:
../RibiLibraries/Wt.pri:
../RibiLibraries/WebApplication.pri:
../RibiClasses/CppAbout/CppAbout.pri:
../RibiClasses/CppFileIo/CppFileIo.pri:
../RibiClasses/CppHelp/CppHelp.pri:
../RibiClasses/CppMenuDialog/CppMenuDialog.pri:
../RibiClasses/CppTestTimer/CppTestTimer.pri:
../RibiClasses/CppTrace/CppTrace.pri:
../RibiLibraries/GeneralConsole.pri:
../RibiClasses/CppWtAboutDialog/CppWtAboutDialog.pri:
../RibiClasses/CppWtAutoConfig/CppWtAutoConfig.pri:
../RibiLibraries/GeneralWeb.pri:
../RibiClasses/CppCanvas/CppCanvas.pri:
../RibiClasses/CppConnectThree/CppConnectThree.pri:
../RibiClasses/CppConnectThreeWidget/CppConnectThreeWidget.pri:
../RibiClasses/CppDotMatrix/CppDotMatrix.pri:
../RibiClasses/CppTextCanvas/CppTextCanvas.pri:
../RibiClasses/CppWtConnectThreeWidget/CppWtConnectThreeWidget.pri:
ConnectThreeConsole.pri:
ConnectThreeWebsite.pri:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resolve_config.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds_post.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_post.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/console.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/rtti.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/precompile_header.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/warn_on.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resources.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/moc.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/opengl.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/testcase_targets.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exceptions.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/yacc.prf:
../RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/lex.prf:
ConnectThreeWebsite.pro:
/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Gui.prl:
/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Core.prl:
/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/platforms/qwindows.prl:
/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qdds.prl:
/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qicns.prl:
/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qico.prl:
/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qjp2.prl:
/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qmng.prl:
/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qtga.prl:
/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qtiff.prl:
/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qwbmp.prl:
/home/p230198/GitHubs/RibiLibraries/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qwebp.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ConnectThreeWebsite.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) /home/p230198/GitHubs/ConnectThree/connectthreewebsite_plugin_import.cpp

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
